version: '2'
services:
  web:
    image: nginx:1.10.1-alpine
    environment:
      VIRTUAL_HOST: web.myapplication.dev
    links:
      - php
    networks:
      - darthaud
    volumes:
      - .:/app
      - ./docker/nginx/my-application.conf:/etc/nginx/conf.d/my-application.conf
  php:
    image: php:7.0.12-fpm-alpine
    networks:
      - darthaud
    volumes:
      - .:/app
networks:
  darthaud:
    external:
      name: darthaud
