version: '2'
services:
  web:
    image: nginx:1.10.1-alpine
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx/my-application.conf:/etc/nginx/conf.d/my-application.conf
  php:
    image: php:7.0.12-fpm-alpine
    volumes:
      - .:/app
